/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Aluno;
import classes.Turma;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author aaaaaaaaaaaaaaaaaaaa
 */
public class TelaAlunos extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlunos
     */
    
    private ArrayList <Aluno> listaAlunos;
    private ArrayList <Turma> listaTurmas;
    TableRowSorter <TableModel> tableSorter ;

    
    private boolean alterar;
    
    public TelaAlunos() {
        initComponents();
        listaTurmas = Turma.carregarLista();
        listaAlunos = Aluno.carregarLista();
        
        carregarComboBox(jComboBoxTurma);
        carregarTable(jTablePesquisa);
        
        addValueChanged(jTablePesquisa);
        
        tableSorter = new TableRowSorter<>(jTablePesquisa.getModel());
	jTablePesquisa.setRowSorter(tableSorter);
      
		 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTurma = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alunos");
        setIconImage(new ImageIcon("icons/aluno.png").getImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel1.setText("Nome");

        jLabel3.setText("Sobrenome");

        jTextFieldNome.setEnabled(false);

        jTextFieldSobrenome.setEnabled(false);

        jLabel4.setText("Turma");

        jComboBoxTurma.setEnabled(false);

        jLabel2.setText("Matrícula");

        jTextFieldMatricula.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jTextFieldSobrenome))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.setFocusCycleRoot(true);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.setFocusCycleRoot(true);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.setFocusCycleRoot(true);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.setFocusCycleRoot(true);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setEnabled(false);
        jButtonLimpar.setFocusCycleRoot(true);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel5.setText("Pesquisar");

        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "Matrícula", "Turma"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePesquisa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTablePesquisa);
        if (jTablePesquisa.getColumnModel().getColumnCount() > 0) {
            jTablePesquisa.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAlterar, jButtonCancelar, jButtonExcluir, jButtonLimpar, jButtonNovo, jButtonSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonLimpar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAlterar, jButtonCancelar, jButtonExcluir, jButtonLimpar, jButtonNovo, jButtonSalvar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparComponents();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        setComponents(false,true,true,true,false,false,true);
        limparComponents();
        jTablePesquisa.clearSelection();
        alterar = false;
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        Aluno aluno = new Aluno();
        aluno.setNome(jTextFieldNome.getText());
        aluno.setSobrenome(jTextFieldSobrenome.getText());
        try{
           aluno.setCodigo(Integer.parseInt(jTextFieldMatricula.getText())); 
        }
        catch(NumberFormatException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Valor inválido para matrícula");
            jTextFieldMatricula.requestFocus();
            return;
        }
        
        
        int indexCombo = jComboBoxTurma.getSelectedIndex();
        if(indexCombo == -1){
            JOptionPane.showMessageDialog(null, "Selecione uma turma para o aluno");
            return;
        }
        aluno.setTurma( listaTurmas.get( indexCombo - 1 ) );
        
        
        if(alterar){
           int indexTable = jTablePesquisa.getSelectedRow();
           if(indexTable == -1){
               return;
           }
           indexTable = tableSorter.convertRowIndexToModel(indexTable);
            
           aluno.setCodigo( listaAlunos.get( indexTable ).getCodigo() );
           boolean exito = aluno.alterar();
            if(exito){
              JOptionPane.showMessageDialog(null,"Aluno " + aluno.getNome() +" " + aluno.getSobrenome() + " Alterado com sucesso");
            }
            else{
                JOptionPane.showMessageDialog(null,"Não foi possível alterar os dados aluno,"
                        + " verifique se todos os campos foram preenchidos corretamente");
                return;
            } 
            
        }
        else{    
            boolean exito = aluno.salvar();
            if(exito){
              JOptionPane.showMessageDialog(null,"Aluno " + aluno.getNome() +" " + aluno.getSobrenome() + " Salvo com sucesso");  
            }
            else{
                JOptionPane.showMessageDialog(null,"Não foi possível salvar o aluno,"
                        + " verifique se todos os campos foram preenchidos");
                return;
            }
        }
        
        listaAlunos = Aluno.carregarLista();
        carregarTable(jTablePesquisa);
        setComponents(true,false,false,false,false,false,false);
                       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        setComponents(false,true,true,true,false,false,true);
        alterar = true;
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setComponents(true,false,false,false,false,false,false);
        limparComponents();
        jTablePesquisa.clearSelection();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
              
       int index = jTablePesquisa.getSelectedRow();    
       if(index == -1){
           return;
       }
       index = tableSorter.convertRowIndexToModel(index);
       
       int opcao;       
        Object[]botoes = {"Sim", "Não"};
        opcao = JOptionPane.showOptionDialog(null,
                "Deseja mesmo excluir o cadastro " + listaAlunos.get(index).getNome(), "Fechar",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,
                null,botoes,botoes[0]);
        if(opcao == JOptionPane.NO_OPTION){
            return;
        }

       boolean exito = listaAlunos.get(index).excluir();
       if(exito){
           listaAlunos = Aluno.carregarLista();
           jTablePesquisa.clearSelection();
           limparComponents();
           carregarTable(jTablePesquisa);
           setComponents(true,false,false,false,false,false,false);
           JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
       }
       else{
           JOptionPane.showMessageDialog(null,"Não foi possível realizar a exclusão");
       }
      
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        String text = jTextFieldPesquisar.getText();		
        if(text.trim().length() != 0)
        {
            tableSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));    
        }
        else{
            tableSorter.setRowFilter(null);
        }
    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

   private void addValueChanged(JTable jTable){
       
       // classe interna anônima
        jTable.getSelectionModel().addListSelectionListener(
            new javax.swing.event.ListSelectionListener() {
                
                @Override
                public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    
                    // preventing from double events
                    if(!evt.getValueIsAdjusting() ){
                        int index = jTablePesquisa.getSelectedRow();
                        if(index == -1){
                            return;
                        }    
                        index = tableSorter.convertRowIndexToModel(index);
                        
                        jTextFieldNome.setText(listaAlunos.get(index).getNome());
                        jTextFieldSobrenome.setText(listaAlunos.get(index).getSobrenome());
                        jComboBoxTurma.setSelectedItem(listaAlunos.get(index).getTurma().getDescricao());
                        jTextFieldMatricula.setText("" + listaAlunos.get(index).getCodigo());
                        
                        setComponents(true, false, false, false, true, true, false);
                        
                    }
                    
                }
            }
        );     
   }
   

    
    
    private void limparComponents(){
        jTextFieldNome.setText("");
        jTextFieldSobrenome.setText("");
        jTextFieldMatricula.setText("");
        jComboBoxTurma.setSelectedItem(null);
    }
    
    private void setComponents(boolean novo, boolean limpar, boolean salvar,
            boolean cancelar, boolean excluir, boolean alterar, boolean texto){
        jButtonNovo.setEnabled(novo);
        jButtonLimpar.setEnabled(limpar);
        jButtonSalvar.setEnabled(salvar);
        jButtonCancelar.setEnabled(cancelar);
        jButtonExcluir.setEnabled(excluir);
        jButtonAlterar.setEnabled(alterar);
        
        jTextFieldNome.setEnabled(texto);
        jTextFieldSobrenome.setEnabled(texto);
        jComboBoxTurma.setEnabled(texto);
        jTextFieldMatricula.setEnabled(texto);
        
        
    }
    
    
    private void carregarComboBox(JComboBox comboBox){   
        if(listaTurmas != null){          
            int tamanho = listaTurmas.size();   
            String nomesTurmas[] = new String[tamanho + 1];
            nomesTurmas[0] = "";
            
            for(int i = 0; i < tamanho; i++){
                nomesTurmas[i+1] = listaTurmas.get(i).getDescricao();               
            }                   
            comboBox.setModel( new DefaultComboBoxModel( nomesTurmas ) ); 
        }
                
    }
    
     
    private void carregarTable(JTable jTable){

     

        if(listaAlunos != null){
            
            int tamanho = listaAlunos.size();
            String dadosAlunos[] = new String[4];
            DefaultTableModel model;         
            model = (DefaultTableModel) jTable.getModel();
            
            // limpando para evitar lixo ao atualizar a table
            int quantidadeLinhas = model.getRowCount();
            for(int i = 0; i < quantidadeLinhas; i++){
                model.removeRow(0);
            }
                                  
            for(int i = 0; i < tamanho; i++){
                dadosAlunos[0] = listaAlunos.get(i).getNome();
                dadosAlunos[1] = listaAlunos.get(i).getSobrenome();
                dadosAlunos[2] = String.valueOf(listaAlunos.get(i).getCodigo());
                dadosAlunos[3] = listaAlunos.get(i).getTurma().getDescricao();
                
                model.addRow(dadosAlunos);
            }
            
            jTable.setModel( model );                       
        }      
    }
      
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonAlterar;
    javax.swing.JButton jButtonCancelar;
    javax.swing.JButton jButtonExcluir;
    javax.swing.JButton jButtonLimpar;
    javax.swing.JButton jButtonNovo;
    javax.swing.JButton jButtonSalvar;
    javax.swing.JComboBox<String> jComboBoxTurma;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JPanel jPanel1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTable jTablePesquisa;
    javax.swing.JTextField jTextFieldMatricula;
    javax.swing.JTextField jTextFieldNome;
    javax.swing.JTextField jTextFieldPesquisar;
    javax.swing.JTextField jTextFieldSobrenome;
    // End of variables declaration//GEN-END:variables
}
